### ISSUE TITLE
Jupyter Images are not rendering

### ISSUE THREAD

**Issue by blaine12100** [Yorko/mlcourse.ai#661]
Hi

Thanks for launching such an awesome course. I am really enjoying working with this material. However, I am facing a small issue right now.

After cloning the repo and running the notebooks, it seems that the images are not getting rendered correctly. I have not moved the path of the Images and I have verified that the images themselves exist in the location mentioned in the img src of the image.
![Screenshot from 2020-04-05 19-09-25](https://user-images.githubusercontent.com/18356070/78499880-08bf8380-7771-11ea-8021-fd09a4211070.png)
![Screenshot from 2020-04-05 19-09-30](https://user-images.githubusercontent.com/18356070/78499883-09f0b080-7771-11ea-8bb9-19eac141ebe8.png)

I have attached a list of the pictures which might help you. I am using jupyter notebook to work with the notebooks locally alogn with Python3 3.6.9

**Comment by Yorko** [comment]
Hi, thanks!

The image that you mention is there in the repo https://github.com/Yorko/mlcourse.ai/blob/master/img/SCORE_CVD_eng.png.

So double check that you specify the correct path, and it will we rendered. Maybe you moved the notebook somewhere so that the path `../../img/SCORE_CVD_eng.png` is not valid anymore. 

You can check that from the notebook itself: `!ls ../../img/SCORE_CVD_eng.png` or `import os; os.path.exists('../../img/SCORE_CVD_eng.png')`

**Comment by blaine12100** [comment]
Hi

Why is this issue closed?

**Comment by Yorko** [comment]
Hi! It's not actually an issue, it's a question which I already addressed.

**Comment by blaine12100** [comment]
Oh

Then can you direct me to the solution and I am currently running the code
locally on my system.

**Comment by Yorko** [comment]
See my [comment above](https://github.com/Yorko/mlcourse.ai/issues/661#issuecomment-612432207)

**Comment by blaine12100** [comment]
Sorry for that

The path is indeed valid as I have not moved the notebook or anything

Anyways I will have a look at it

Thanks for your advice Mr Yorko

**Comment by blaine12100** [comment]
Hi
Solved the Issue.
The issue was the location from where I was starting the notebook in
Thanks for helping me and thank you for making such a good course :-)
